const FETCH_APPLICATIONS = "FETCH_APPLICATIONS";
const GET_APPLICATION = "GET_APPLICATION";
const ADD_APPLICATION = "ADD_APPLICATION";
const DELETE_APPLICATION = "DELETE_APPLICATION";

export {
	FETCH_APPLICATIONS,
	GET_APPLICATION,
	ADD_APPLICATION,
	DELETE_APPLICATION,
};
